### ISSUE TITLE
シーンサイズとタイトル画面

### ISSUE THREAD

**Issue by Reputeless** [sknjpn/SyLife#52]
2560x1440 以外の解像度や、2560x1440 でも OS で UI スケールを 100% 以外に設定している場合、タイトル画面でボタンが表示されません。
![20220105-194935-441](https://user-images.githubusercontent.com/3108136/148205654-2d5d2c8c-f45a-4da6-a9fa-5858136c1f0c.png)

関連するかはわかりませんが、v0.6 で Scene のリサイズの仕組みが変更されている点に注意です。
https://zenn.dev/reputeless/books/siv3d-documentation/viewer/tutorial-scene#15.1-%E4%B8%89%E3%81%A4%E3%81%AE%E3%82%B5%E3%82%A4%E3%82%BA

解決策として、
```cpp
  Window::SetStyle(WindowStyle::Sizable);
  Scene::Resize(2560, 1440);

  // Window設定
  if (GeneralSetting::GetInstance().m_fullScreenEnabled) {
    Window::SetFullscreen(true); // ここでシーンのサイズが変わる
  } else {
    Window::Maximize(); // ここでシーンのサイズが変わる
  }
```
を
```cpp
  Window::SetStyle(WindowStyle::Sizable);
  Scene::SetResizeMode(ResizeMode::Keep); // シーンのサイズは、ウィンドウサイズが変わっても変わらないようにする
  Scene::Resize(2560, 1440);

  // Window設定
  if (GeneralSetting::GetInstance().m_fullScreenEnabled) {
    Window::SetFullscreen(true);
  } else {
    Window::Maximize();
  }
```

に変更することで、手元の環境では正しく表示されるようになりました。

**Comment by sknjpn** [comment]
問題確認しました。
調査したところ、UIスケールが100%でない場合はScene::Size()が最初のSystem::Update()の後に変更されるため、System::Update()前に配置を決定するUI表示が乱れるようです。
基本的に起動時にシーンのサイズを固定する方式に変更しようと思います。

**Comment by Reputeless** [comment]
`Window::Maximize()` ですぐにシーンサイズが更新されないの、Siv3D 側で改善すべき問題かもしれません。
OpenSiv3D の Issue にしておきました。検証ありがとうございます。
https://github.com/Siv3D/OpenSiv3D/issues/722

**Comment by sknjpn** [comment]
承知いたしました。
ありがとうございます。
